import mongoose from "mongoose";

const categoryTopics = {
    Aptitude: [
        "Number System",
        "Simplification and Approximation",
        "HCF and LCM",
        "Decimal Fractions",
        "Percentage",
        "Profit and Loss",
        "Simple Interest",
        "Compound Interest",
        "Ratio and Proportion",
        "Partnership",
        "Average",
        "Alligation and Mixtures",
        "Problems on Ages",
        "Time and Work",
        "Pipes and Cisterns",
        "Time, Speed and Distance",
        "Problems on Trains",
        "Boats and Streams",
        "Permutation and Combination",
        "Probability",
        "Arithmetic Progression",
        "Geometric Progression",
        "Quadratic Equations",
        "Logarithms",
        "Surds and Indices",
        "Algebra",
        "Geometry",
        "Mensuration",
        "Coordinate Geometry",
        "Trigonometry",
        "Data Interpretation",
        "Data Sufficiency",
        "Venn Diagram",
        "Series",
        "Calendar",
        "Clocks"
    ],
    Reasoning: [
        "Introduction to Logical Reasoning",
        "Direction Sense",
        "Blood Relations",
        "Coding-Decoding",
        "Alphabet Series",
        "Number Series",
        "Alphanumeric Series",
        "Linear Arrangement",
        "Circular Arrangement",
        "Puzzles",
        "Ranking and Order",
        "Syllogism",
        "Statement and Conclusion",
        "Statement and Assumption",
        "Statement and Argument",
        "Cause and Effect",
        "Assertion and Reason",
        "Data Sufficiency",
        "Analogy",
        "Classification",
        "Logical Sequence",
        "Calendar",
        "Clocks",
        "Cube and Dice",
        "Mirror Image",
        "Water Image",
        "Paper Folding",
        "Paper Cutting",
        "Figure Counting",
        "Embedded Figures",
        "Figure Analogy",
        "Figure Classification",
        "Non-Verbal Series",
        "Critical Reasoning",
        "Decision Making"
    ],
    Verbal: [
        "Introduction to Verbal Reasoning",
        "Advice and Expectations",
        "Reading Comprehension",
        "Sentence Ordering",
        "Sentence Completion",
        "Fill in the Blanks",
        "Cloze Test",
        "Error Identification",
        "Sentence Improvement",
        "Sentence Correction",
        "Para Jumbles",
        "Paragraph Completion",
        "Vocabulary",
        "Synonyms",
        "Antonyms",
        "One Word Substitution",
        "Idioms and Phrases",
        "Spellings",
        "Active and Passive Voice",
        "Direct and Indirect Speech",
        "Tenses",
        "Subject-Verb Agreement",
        "Articles",
        "Prepositions",
        "Conjunctions",
        "Pronouns",
        "Nouns",
        "Verbs",
        "Adjectives",
        "Adverbs",
        "Punctuation"
    ],
    Technical: [
        "Programming Fundamentals",
        "C Programming",
        "C++",
        "Java",
        "Python",
        "JavaScript",
        "Object-Oriented Programming",
        "Data Structures",
        "Algorithms",
        "Time Complexity",
        "Space Complexity",
        "Recursion",
        "Arrays",
        "Strings",
        "Linked Lists",
        "Stack",
        "Queue",
        "Hashing",
        "Trees",
        "Binary Search Tree",
        "Heap",
        "Trie",
        "Graphs",
        "Dynamic Programming",
        "Greedy Algorithms",
        "Backtracking",
        "Searching",
        "Sorting",
        "DBMS",
        "SQL",
        "Operating System",
        "Computer Networks",
        "Software Engineering",
        "HTML",
        "CSS",
        "React.js",
        "Node.js",
        "Express.js",
        "REST API",
        "Authentication",
        "MongoDB",
        "Git",
        "GitHub",
        "System Design"
    ]
};

const QuestionModel = new mongoose.Schema({
    question: {
        type: String,
        required: true
    },
    options: {
        type: [String],
        required: true
    },
    correctOption: {
        type: Number,
        required: true,
        min: 0,
        max: 3
    },
    category: {
        type: String,
        required: true,
        enum: Object.keys(categoryTopics)
    },
    topic: {
        type: String,
        required: true,
        validate: {
            validator: function (value) {
                return categoryTopics[this.category]?.includes(value);
            },
            message: props => `"${props.value}" is not a valid topic for "${props.instance.category}".`
        }
    },
    difficulty: {
        type: String,
        required: true,
        enum: ["Easy", "Medium", "Hard"]
    },
    explaination: {
        type: String,
        required: true
    }
})

const questionModel = mongoose.model("Question", QuestionModel);

export default questionModel